### ISSUE TITLE
Treasury amounts do not have separators

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/api3-dao-dashboard#298] opened 2022-06-27 15:03 UTC
The amounts do not use commas as separators, which makes them difficult to read
https://forum.api3.org/uploads/db4790/original/2X/6/69eba303e0b763121843ff31663e7a209092ccf3.png

**Comment by Siegrift** [comment] 2022-06-27 16:50
Duplicate of https://github.com/api3dao/api3-dao-dashboard/issues/272

**Closed by Siegrift** 2022-06-27 16:50 UTC
